### ISSUE TITLE
530 Campbellfield Plaza loop- redraw? 

### ISSUE THREAD

**Issue by Craig3196** [philam/melbournetransportmap#14]
Size of loop for 530 at Campbellfield Plaza is quite exaggerated compared to actual size (just looping behind the shopping centre buildings) 

Also, it should be clearer at a glance that 902 serves Campbellfield Plaza on Mahoneys Rd than appearing effectively 500m or more south of the 530 loop

**Comment by philam** [comment]
Moved everything further south and added interchange dot
