### ISSUE TITLE
TeleBus issues

### ISSUE THREAD

**Issue by Craig3196** [philam/melbournetransportmap#21]
Area labels would be useful

Areas 2, 3 & 4 currently not marked on map, but well done on showing Croydon Hills TeleBus area on Route 672 

Peak hour trips on Areas 7 & 8 extend to Ferntree Gully Station as a fixed route through part of Ferntree Gully, this could be drawn as either a grey line or faint pink line. Refer to Knox Local Area Map.

**Comment by philam** [comment]
Added peak trips for Areas 7&8
