### ISSUE TITLE
623 via Mt Waverley

### ISSUE THREAD

**Issue by Craig3196** [philam/melbournetransportmap#34]
Need label to show 623 runs to Mt Waverley Station, possibly with stub up Miller Cres on northern side of rail line

**Comment by philam** [comment]
Done, and rearranged some labels too to make it more clear (hopefully).

![mountwalvery](https://user-images.githubusercontent.com/6771240/71655376-82b72980-2d8a-11ea-8d2f-2dc8af3053ed.PNG)
