### ISSUE TITLE
765 via Blackburn

### ISSUE THREAD

**Issue by Craig3196** [philam/melbournetransportmap#35]
765 not shown to operate via Blackburn at present

Look at the route map for some clarification as it runs via Main St towards Mitcham only, due to right hand turn issues

**Comment by philam** [comment]
This is still thoroughly confusing to me, but fixed on the map

**Comment by Craig3196** [comment]
Are you going to release a weekly update of the map with the changes as you go? Disappointed the website map hasn't reflected these changes yet!

**Comment by Craig3196** [comment]
Great effort Phil though, happy to lend my knowledge for this amazing project

**Comment by philam** [comment]
Thanks @Craig3196 and for all your great help! I'm going to release all the changes at once, when I finish going through them all. That will probably be a few days
