### ISSUE TITLE
708, 857 & 858 in Chelsea Heights

### ISSUE THREAD

**Issue by Craig3196** [philam/melbournetransportmap#96]
708 could be shown to travel on Thames Prom (in line with 858 line) with in turn 858 shown to deviate south-east via Chelsea Park Dr etc 

Unclear if 857 have a terminus dot for its AM peak branch starting in Chelsea Heights? In any case, a south-east arrow can be added along Wells Rd as this trip only operates in one direction

**Comment by philam** [comment]
Reference #86
